name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        python -m pytest tests/test_simple.py -v
        python -c "print('Basic functionality verified')"
    
    - name: Verify app structure
      run: |
        python -c "import app; print('App package imported successfully')"
        ls -la app/

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t customer-query-system .
        echo "Docker build successful"
    
    - name: Verify build
      run: |
        docker images | grep customer-query-system
        echo "Build verification complete"